services:
  db:
    image: database
    container_name: parabible-db
    build: 
      context: ./postgres
    env_file:
      - ./postgres/env_file
    command: -p 5432
    ports:
      - 5432:5432
    networks:
      - db_backend
    
  pgAdmin:
    image: dpage/pgadmin4
    container_name: parabible-pgAdmin
    env_file:
      - ./postgres/env_file
    depends_on:
      - db
    ports: 
      - 80:80
    networks:
      - db_backend

  flask-front:
    image: flask-front
    container_name: parabible-flask
    depends_on:
      - db
    restart: on-failure:5 
    build:
      context: ./web
    env_file:
      - ./web/env_file
    ports:
      - 5000:5000
    networks:
      - db_backend

    # !!!
    # COMMENT THIS TO ENABLE FRONTEND
    #profiles:
    #  - donotstart
    # !!!

networks:
  db_backend:
    name: db_backend